### ISSUE TITLE
Bring back the cheat menu!

### ISSUE THREAD

**Issue by Tehelee** [OpenSWE1R/openswe1r#165]
So it took me a few days of research and work but I've re-enabled the cheat menu that was available on N64. I don't know enough assembly to fully trace out what needs to change to enable the menu using in-game methods alone (I'm not sure if the activation code is still in there), but I identified enough offsets to force it on with full functionality. I think the display is a little messed up but the code is still there.

I've uploaded my work with the Cheat Engine auto assembler and built a standalone executable to patch any instance of the game as it launches. If nothing else the assembly code I do have should be a good head start on bringing this menu back properly for this project.

https://github.com/Tehelee/SWEP1RCR_CM/releases/tag/1.0
(Also maybe add this to the wiki's useful links?)

![swep1rcr_mirroedmode](https://user-images.githubusercontent.com/8411750/43030291-60fddb2a-8c5c-11e8-8b9b-695646d5e1f6.jpg)
![swep1rcr_racerstats](https://user-images.githubusercontent.com/8411750/43030292-6257391c-8c5c-11e8-9d64-e0cf7154c7d2.jpg)

**Comment by JayFoxRox** [comment]
[How the menu works (including the PC release) has been (mostly) documented in swe1r-re](https://github.com/OpenSWE1R/swe1r-re/blob/master/swep1rcr.exe/Debug-Mode.md) which is the reverse engineering project to make openswe1r possible.

We also don't know how to enable it without memory hacks though.

[What we *did* find are the N64 cheats; and those are documented on GOG.com forums by me](https://www.gog.com/forum/star_wars_episode_i_racer/unlocking_jinn_reeso_and_cy_yunga_on_pc_uncovered_after_almost_20_years).
[We also found other debug functionality which were probably *never* used by the public before](https://github.com/OpenSWE1R/swe1r-re/issues/34#issuecomment-390429062).
It is possible that we will find out how to enable the debug menu in the future.
[There are also various hot-keys which have not been documented yet](https://github.com/OpenSWE1R/swe1r-re/pull/23).

Adding this information to TCRF would probably be the best idea to make this information easy to find.

---

However, this is not an issue with openswe1r which just aims to re-implement the original swep1rcr.exe (so we *will* eventually re-implement it, but if the original game has no way to enable it, openswe1r will accurately replicate that).

You can add your tool to https://github.com/OpenSWE1R/openswe1r/wiki/Useful-Resources
Every GitHub user should have edit permissions automatically.

Because this this issue is not a problem or feature we have to track for openswe1r:

Closed.

**Comment by Tehelee** [comment]
Thanks, I had no idea how to contact you about it; I wish I had seen swe1r-re when I was working on this!
I'll keep looking into this and I'll let you know if I find out how to actually activate it without hacks.
