### ISSUE TITLE
Turn off Trigger notifications for HD fonts

### ISSUE THREAD

**Issue by filipinowhiteboy** [OpenSWE1R/openswe1r#186]
Just as the title says, is there a way to turn off Trigger notifications when using HD fonts? they appear during races where an event is triggered. Like breaking rocks, ice or sticks. They can be distracting while running Episode 1 Racer.

**Comment by JayFoxRox** [comment]
This doesn't seem OpenSWE1R related. You might be thinking of https://github.com/JayFoxRox/swe1r-patcher?
However, even in that project, it had been disabled by default since https://github.com/JayFoxRox/swe1r-patcher/pull/29 (early 2019).

Closed as invalid, because OpenSWE1R doesn't contain HD fonts or code to enable triggers.
